language: android

sudo: true

android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'


before_script:
  - cordova platform rm android
  - cordova platform add android
  
install:
  - apt install npm
  - npm cache clean
  - npm install
  - npm install -g cordova

script:
  - cordova prepare
  - cordova build andro
